POST http://localhost:3000/Pdf
Content-Type: text/plain

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <header>
        <h1>This is a hardcoded test</h1>
    </header>
    <div>
        <h2>456789</h2>
    </div>
</body>"

